# Numpy challenge

In [77]:
import numpy as np
import numpy_indexed as npi
from collections import defaultdict
import pandas as pd
from datetime import datetime

Challenge: Return voor elk element het hoeveelste element dat is so far in de array

In [79]:
# example
inp = np.array([7, 7, 7, 8, 7, 8, 8, 9, 9])
outp = np.array([1, 2, 3, 1, 4, 2, 3, 1, 2])

In [82]:
# for loop solution
def for_loop_list(inp):
    counts_so_far = defaultdict(int)
    outp = []
    for i in inp:
        counts_so_far[i] += 1
        outp.append(counts_so_far[i])
        
    return np.array(outp)

for_loop_list(inp)

array([1, 2, 3, 1, 4, 2, 3, 1, 2])

In [83]:
# crazy pandas solution
def pandas_rank(inp):
    df = pd.DataFrame({'u':inp, 'i':inp})
    oui = df.groupby("u")['i'].rank("first")
    return oui.values
    
pandas_rank(inp)

array([1., 2., 3., 1., 4., 2., 3., 1., 2.])

In [97]:
# your submission
def custom_oui(inp):
    dummy = np.zeros_like(inp)
    return dummy

In [98]:
# verify if it works
assert((for_loop_list(inp) == outp).all())
assert((pandas_rank(inp) == outp).all())
assert((custom_oui(inp) == outp).all())

pandas_rank

AssertionError: 

# Timing

In [75]:
time_inp = np.random.randint(1, 100, size=(5000))
time_inp

array([91, 17, 87, ..., 33, 36, 53])

In [99]:
st = datetime.now()

for i in range(1000):
    for_loop_list(time_inp)
    
print("For loop scored:", datetime.now() - st)

For loop scored: 0:00:01.536408


In [100]:
st = datetime.now()

for i in range(1000):
    pandas_rank(time_inp)
    
print("Pandas scored:", datetime.now() - st)

Pandas scored: 0:00:00.740860


In [101]:
st = datetime.now()

for i in range(1000):
    custom_oui(time_inp)
    
print("Pandas scored:", datetime.now() - st)

Pandas scored: 0:00:00.003999
